In [1]:
import numpy as np

In [2]:
a=np.array[[4,2,6],[45,28,69],[1,2,3]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [3]:
a=np.array([[4,2,6],[45,28,69],[1,2,3]])

In [4]:
a


array([[ 4,  2,  6],
       [45, 28, 69],
       [ 1,  2,  3]])

In [5]:
a=np.array[[4,2,6,5],[45,86,28,69],[9,1,2,3]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [6]:
a=np.array([[4,2,6,5],[45,86,28,69],[9,1,2,3]])

In [7]:
a


array([[ 4,  2,  6,  5],
       [45, 86, 28, 69],
       [ 9,  1,  2,  3]])

In [8]:
a[2,3]

3

In [9]:
a[1,2]

28

In [10]:
a[]2


SyntaxError: invalid syntax (143511467.py, line 1)

In [11]:
a[2
 ]

array([9, 1, 2, 3])

In [12]:
n[0,0]

NameError: name 'n' is not defined

In [13]:
n.shape

NameError: name 'n' is not defined

In [14]:
a.shape

(3, 4)

In [15]:
a[2,1:3]

array([1, 2])

In [16]:
a=np.array([[4,2,6,5],[45,86,28,69],[9,1,2,3]])

In [17]:
a

array([[ 4,  2,  6,  5],
       [45, 86, 28, 69],
       [ 9,  1,  2,  3]])

In [18]:
a.shape

(3, 4)

In [19]:
a[2,1:3]

array([1, 2])

In [20]:
a[0,1:4]

array([2, 6, 5])

In [21]:
a[1:3,1:3]

array([[86, 28],
       [ 1,  2]])

In [22]:
a[1:,2:]

array([[28, 69],
       [ 2,  3]])

# Arrange

In [23]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [24]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
np.arange(5.52,62.9)

array([ 5.52,  6.52,  7.52,  8.52,  9.52, 10.52, 11.52, 12.52, 13.52,
       14.52, 15.52, 16.52, 17.52, 18.52, 19.52, 20.52, 21.52, 22.52,
       23.52, 24.52, 25.52, 26.52, 27.52, 28.52, 29.52, 30.52, 31.52,
       32.52, 33.52, 34.52, 35.52, 36.52, 37.52, 38.52, 39.52, 40.52,
       41.52, 42.52, 43.52, 44.52, 45.52, 46.52, 47.52, 48.52, 49.52,
       50.52, 51.52, 52.52, 53.52, 54.52, 55.52, 56.52, 57.52, 58.52,
       59.52, 60.52, 61.52, 62.52])

# Reshape

In [26]:
np.arange(12).reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [27]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [29]:
list(range(1,12))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [30]:
list(range(1,1212))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [31]:
a.min()

1

In [32]:
a=np.array([[1,2,3,4],[85,56,56,58],[78,89,45,54]])

In [33]:
a


array([[ 1,  2,  3,  4],
       [85, 56, 56, 58],
       [78, 89, 45, 54]])

In [34]:
a.min()

1

In [35]:
a.max()

89

In [36]:
a.argmax()

9

In [37]:
a.argmin()

0

In [38]:
a*2

array([[  2,   4,   6,   8],
       [170, 112, 112, 116],
       [156, 178,  90, 108]])

# Random

In [39]:
np.random.rand(2,2)

array([[0.30519035, 0.00636241],
       [0.38401777, 0.98603406]])

In [40]:
a.min()

1

In [41]:
np.random.rand(2)

array([0.22250687, 0.47633426])

In [42]:
np.random.randn(2,2)

array([[-0.52678454, -0.25285412],
       [-0.69976385, -0.79063037]])

In [44]:
np.random.randint(9,90,12).reshape(6,2)

array([[53, 73],
       [21, 47],
       [13, 27],
       [58, 62],
       [69, 84],
       [28, 52]])

In [45]:
a.sum()

531

In [46]:
a.sum(axis=1)

array([ 10, 255, 266])

# 3D

In [50]:
x=np.arr[[[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,46],[6,69]]]

AttributeError: module 'numpy' has no attribute 'arr'

In [48]:
d.shape

NameError: name 'd' is not defined

In [49]:
x.shape

NameError: name 'x' is not defined

In [51]:
x.shape

NameError: name 'x' is not defined

In [53]:
d=np.array[[[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,46],[6,69]]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [55]:
d=np.array([[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,46],[6,69]])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [57]:
d=np.array([[[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,46],[6,69]]])

In [58]:
d=np.array([[[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,46],[6,69]]])

In [59]:
d.shape

(3, 3, 2)

In [60]:
x.dtype

NameError: name 'x' is not defined

# NAN-not a number

In [61]:
x=np.array([12,56,np.nan])

In [62]:
x.dtype

dtype('float64')